### ISSUE TITLE
nodemon 

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#1]
Les sugiero fuertemente, especialmente ahora que vamos a empezar a modificar más los js, que instalen y utilicen un script que tenga nodemon (además del que ya tienen)

**Comment by magali-anglada** [comment]
Nodemone was installed in development scope.
The following script has been added in  package.json file
 "dev": "nodemon src/app.js"

Nodemon has been installed and the dependence was added in package.json file
 "devDependencies": {
    "nodemon": "^3.0.1"
  }
