### ISSUE TITLE
lógica del negocio

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#10]
misma idea que los productos con decuento

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/3ba6be169a3a36d2703541a156ebc47297017ce6/src/controllers/products-controller.js#L29-L31

**Comment by magali-anglada** [comment]
Esperando feedback en Issue #09

**Comment by magali-anglada** [comment]
Ya fue ajustado. Descripción en issue  #9
