### ISSUE TITLE
mejor booleano

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#11]
En vez de recibir una X o un string vacío no tiene más lógica que reciba un booleano?

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/3ba6be169a3a36d2703541a156ebc47297017ce6/src/controllers/products-controller.js#L30

**Comment by magali-anglada** [comment]
Se modificó para tratarse como un booleano (que es como esté definido en la base de datos ahora. Se puede en donde fue movida la lógica

https://vscode.dev/github/0623CIFSNCN05LAED/grupo-05/blob/main/src/data/products/products.js#L16
