### ISSUE TITLE
Eliminar método vacío

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#13]
En general no es buena idea dejar elementos sin funcionalidad que sólo traen ruido

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/3ba6be169a3a36d2703541a156ebc47297017ce6/src/controllers/users-controller.js#L31-L32

**Comment by magali-anglada** [comment]
Eliminado @LuiosDyet
