### ISSUE TITLE
desloguear al eliminar

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#14]
Cuando eliminan a un usuario también deberían desloguerlo, sino imagino que queda en session un usuario que no existe y eso seguro es para problemas

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/3ba6be169a3a36d2703541a156ebc47297017ce6/src/controllers/users-controller.js#L118-L121

**Comment by magali-anglada** [comment]
Se adición el req.session.destroy() para terminar la sesión. 

https://vscode.dev/github/0623CIFSNCN05LAED/grupo-05/blob/main/src/controllers/users-controller.js#L118
