### ISSUE TITLE
lógica de asignación de colors y sizes

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#16]
No para que se maten con esto ya que se resuelve usando tablas relacionales, pero la lógica no debería ser que asigne colores y tamaños en base al id que maneja el producto?
acá lo que están haciendo es asignarles los primero n colores o tamaños dependiendo de los elementos del array de esa propiedad en el json

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/3ba6be169a3a36d2703541a156ebc47297017ce6/src/services/product-services.js#L34-L42

**Comment by magali-anglada** [comment]
Hola @LuiosDyet esta lògica ya no està asì. Implemente dos relaciones ManyToMany entre productos y los colores y tamaños. Eso ya quedó funcionando sin inconvenientes y creo que està bien implementado ahora (tu feedback sería valioso).

Lo que necesito ahora es un poquito de claridad o algun entryPoint para tener màs claro como se manejan los creates y updates con este tipo de relaciones. Así como al tener las relaciones e incluir/extender atravès del alias en lo que es lectura (findAll, findByKey)... como se hace a la hora de insertar o actualizar? Se crea el producto y luego por separado se crea el registro en la tabla de relaciòn (como dos pasos manuales) o existe una operación que resuelta ambas cosas en un mismo paso?  Me podrás dar una punta de ayuda con esto? Me gsutarìa dejarlo implementado con ManyToMany pero tengo ahora el hueco en la actualización.

Millones de gracias!

**Comment by magali-anglada** [comment]
@LuiosDyet  ya implementé la solución y quedò funcionando. No se si es la mejor y màs optima ni si asì se suele hacer pero anda :). 
Queda el issue para tu revisión y cierre.
Gracias.
