### ISSUE TITLE
Tipo de domicilio en el detalle del usuario

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-05#18]
En la vista del detalle de usuario, aparentemente hay una mala interpretación de la vista del campo de Tipo de domicilio.
Este parece mostrar como que el tipo existente es un mensaje de Sequelize (que nunca debería llegar a la vista)

**Comment by magali-anglada** [comment]
@LuluAylen00  issue solucionado. Se ajustó la vista user-detail.ejs
