### ISSUE TITLE
Dos rutas para una misma vista

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#2]
No estoy muy seguro de cuál es la lógica por al cuál tienen dos rutas que apuntan a la misma vista. No es muy ortodoxo pero capaz existe una lógica de negocio que desconozco que les llevó a esta decisión. 

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/4ba8b84289a1baacde4a3af5ab7d55ae4687c74b/src/app.js#L15-L21

**Comment by magali-anglada** [comment]
Issue solucionado en última versión. Solo se dejo el /.

Por favor validar. 

Gracias!
