### ISSUE TITLE
nombre de archivos en kebab-case

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#3]
Les sugiero que utilicen kebab-case en vez de camelCase para los nombre de archivos. Les va a ahorrar dolores de cabeza en el futuro

**Comment by magali-anglada** [comment]
The productCart and productDetail files were renamed to productcart and productdetail.

Additionally, in the HEADER the reference to the productCart was renamed.

**Comment by LuiosDyet** [comment]
kebab-case es con guion entre palabras

**Comment by magali-anglada** [comment]
Error de usuario (programador) :)
Issue solucionado... por favor validar en la actual version
