### ISSUE TITLE
Idioma del sitio

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#4]
Más que nada para traductores y SEO, que no es un detalle.

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/4ba8b84289a1baacde4a3af5ab7d55ae4687c74b/src/views/index.html#L2

**Comment by magali-anglada** [comment]
The language of the site is set to Spanish through the <html lang="es"> tag
