### ISSUE TITLE
Trello público

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#5]
Podrán cambiar la privacidad el trello a público para que podamos acceder, gracias!!

Por otro lado noté que tienen varios trellos, deberían tener uno para todo el proyecto, no uno por sprint

**Comment by magali-anglada** [comment]
El projecto en Trello ya se encuentra público, por favor validar.
 
En breve se va a unificar en un úncio backlog para el proyecto.

**Comment by LuiosDyet** [comment]
![image](https://github.com/0623CIFSNCN05LAED/grupo-05/assets/81197487/6459732a-ad46-46f9-9537-82de96cdf10a)

**Comment by magali-anglada** [comment]
El nuevo tablero de trello es el siguiente https://trello.com/b/fWbCBZ2v/devvision-backlog
Ya se encuentra actualizado en el README.MD y está público, Podrás validarlo?

Millones de gracias!
