### ISSUE TITLE
Image ratio

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#6]
Los invito a chusmear estas opciones https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit para ver si pueden hacer que no queden deformes la imágenes

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/4ba8b84289a1baacde4a3af5ab7d55ae4687c74b/src/views/productCart.html#L62

**Comment by polarcit0** [comment]
¡Buenas! Subí el cambio del css con la propiedad object-fit para las imágenes.
