### ISSUE TITLE
Separación de vistas Creación-Edición

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-05#7]
Tengan en cuenta que las vistas de creación y edición de producto, si bien son parecidas, se tratarían de dos vistas completamente distintas! (pues cada una tendrá una funcionalidad asociada).

**Comment by Jkoury997** [comment]
Ya esta separada la vista de creacion y de edicion de productos

**Comment by magali-anglada** [comment]
@LuluAylen00  se puede cerrar este issue u observas algo que debemos de corregir?

Gracias por tu feedback.

Equipo 05

**Comment by LuluAylen00** [comment]
Buenas tardes.
Todo se ve bien! 
Pueden cerrar toda issue nomas cuando estén realmente seguros de haberla solucionado.
