### ISSUE TITLE
Mover multer a su propio módulo

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#8]
Mejor en su propio módulo ya que no es responsabilidad de la ruta saber cómo se guardan las imágenes

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/3ba6be169a3a36d2703541a156ebc47297017ce6/src/routes/products-router.js#L10-L23

lo mismo en las rutas de usuarios

**Comment by Jkoury997** [comment]
Ya esta arreglado, se creo dos middewares uno para productos y otro para users
