### ISSUE TITLE
lógica del negocio

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-05#9]
cuales son los productos con descuento es una lógica de negocio y por lo tanto tiene más sentido que vaya en el servicio

https://github.com/0623CIFSNCN05LAED/grupo-05/blob/3ba6be169a3a36d2703541a156ebc47297017ce6/src/controllers/products-controller.js#L19-L21

**Comment by magali-anglada** [comment]
Tenés razón y ha sido movida, sin embargo tengo una duda más de arquitectura que hoy compartiamos con Andrés también. 
Cuando trabajabamos con los datos a nivel de Json teníamos una carpeta /data y dentro manejabamos dos carpetas más para lo que estaba relacionado con la entidad Producto y con la entidad Usuario. Dentro de la carpeta Producto tenìamos tanto el Json con la información de los productos como un product.js con el comportamiendo de la manipulación de los datos en el JSON. Es decir que en este archivo product.js tenìa los mètodos que accedian a la información, los que hacìan la gestión en el archivo. 

Estos dos archivos los requerìamos en el db.js que contenía la lógica siguiente:

![image](https://github.com/0623CIFSNCN05LAED/grupo-05/assets/51236027/3891c010-b1d0-483f-a353-370bd34fb249)

Ahora bien, cuando pasamos a reemplazar los archivos json por las tablas en la base de datos, esta carpeta /data sigue teniendo sentido y todo lo que es acceso directo a la base de datos ( es decir lo que invoca las promesas findAll, findByPk, create, update, destroy) debe estar allì encapsulado como buena práctica? o todos estos servicos van al product-services.js.

Si ves en la versión que subí donde ya no se trabaja con el Json de productos, la lògica de acceso a la base de datos la puse en este data/products/products.js  y en lo personal me gusta que estè ahì todo lo dependiente de la base de datos. Está bien como está implementado ahora la obtención de la informacion de Descuentos y novedades?

De ser esta manera, cada entidad deberìa tener aquì su archivo, es decir ademas de products y users, lo que hace a brands, genders, colors, sizes debería encapsultarse por entidad tambièn? Porque eso hoy està de manera directa dentro de /services/ en sizes-services,js, genders-services.js, colors-services.js y sizes-services.js. 

Creo que o todo deberìa ir al data por entidad o todo a nivel de los servicios. Podrías darnos tu feedback sobre esto?

Milllones de gracias!!!!!!

**Comment by magali-anglada** [comment]
Ya fue ajustada tal como se conversó en la clase. Se elimino la carpeta data/products y la lógica en el js se llevo directamente al servidio de productos.
